<?php

/**
 * @file
 * Collabco Group module.
 */

/**
 * Implements hook_menu().
 */
function collabco_group_menu() {
  $items = array();
  $items['node/%node/add/member'] = array(
    'title' => 'Add a member',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('collabco_group_add_user_form', 1),
    'access callback' => 'collabco_group_add_user_access',
    'access arguments' => array(1),
  );
  return $items;
}

/**
 * Implementation of form for adding users to a group.
 */
function collabco_group_add_user_form($form, &$form_state, $node) {
  module_load_include('inc', 'og_ui', 'og_ui.admin');
  $form = og_ui_add_users($form, $form_state, 'node', $node->nid);
  $form['og_user']['roles']['#access'] = FALSE;
  $form['membership_fields']['og_membership_request']['#access'] = FALSE;
  $form['og_user']['name']['#title'] = "Start typing a name or email";
  return $form;
}

/**
 * Validate handler; Add users to group.
 */
function collabco_group_add_user_form_validate($form, &$form_state) {
  og_ui_add_users_validate($form, $form_state);
}

/**
 * Submit handler; Add users to group.
 */
function collabco_group_add_user_form_submit($form, &$form_state) {
  og_ui_add_users_submit($form, $form_state);
}

/**
 * Access check for form collabco_group_add_user_form.
 */
function collabco_group_add_user_access($node) {
  if (!og_is_group('node', $node)) {
    return FALSE;
  }
  $gid = $node->nid;
  $is_group_admin = og_user_access('node', $gid, 'administer group');
  if (user_access('administer group') || og_user_access('node', $gid, 'add user')) {
    return TRUE;
  }
  return FALSE;
}
