; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.43"

projects[views_bulk_operations][version] = "3.3"

projects[addressfield][version] = "1.2"

projects[admin_menu][version] = "3.0-rc5"

projects[advanced_help_hint][version] = "1.2"

projects[backup_migrate][version] = "3.1"

projects[better_exposed_filters][version] = "3.2"

projects[better_formats][version] = "1.0-beta2"

projects[block_class][version] = "2.3"

projects[block_revisions][version] = "1.0+0-dev"

projects[ctools][version] = "1.9"

projects[captcha][version] = "1.3"

projects[ckeditor][version] = "1.17"

projects[ckeditor_media][version] = "1.x-dev"

projects[colorbox][version] = "2.10"

projects[colorbox_node][version] = "3.5"

projects[comment_sort_created][version] = "1.0-beta1"

projects[connector][version] = "1.0-beta2"

projects[content_access][version] = "1.2-beta2"

projects[context][version] = "3.6"

projects[creative_commons][version] = "1.2"

projects[css_injector][version] = "1.10"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[disable_messages][version] = "1.1"

projects[email][version] = "1.3"

projects[email_registration][version] = "1.3"

projects[entity][version] = "1.7"

projects[entity2text][version] = "1.0-alpha3"

projects[entity_rules][version] = "1.0-alpha4"

projects[entityconnect][version] = "1.0-rc5"

projects[entityform][version] = "2.0-rc1"

projects[entityreference][version] = "1.1"

projects[features_extra][version] = "1.0"

projects[features][version] = "2.10"

projects[features_override][version] = "2.0-rc3"

projects[feeds][version] = "2.0-beta2"

projects[field_collection][version] = "1.0-beta11"

projects[field_collection_fieldset][version] = "2.6"

projects[field_group][version] = "1.5"

projects[filefield_nginx_progress][version] = "2.3"

projects[flag][version] = "3.7"

projects[flood_control][version] = "1.0"

projects[fpa][version] = "2.6"

projects[google_analytics][version] = "2.2"

projects[honeypot][version] = "1.22"

projects[image_url_formatter][version] = "1.4"

projects[imce][version] = "1.10"

projects[inline_entity_form][version] = "1.8"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.7"

projects[js_injector][version] = "2.1"

projects[libraries][version] = "2.2"

projects[link][version] = "1.4"

projects[list_predefined_options][version] = "1.0"

projects[login_destination][version] = "1.4"

projects[login_history][version] = "1.0-beta3"

projects[logintoboggan][version] = "1.5"

projects[mail_edit][version] = "1.1"

projects[mailsystem][version] = "2.34"

projects[mandrill][version] = "1.6"

projects[masquerade][version] = "1.0-rc7"

projects[mass_contact][version] = "1.1"

projects[menu_attributes][version] = "1.0"

projects[menu_token][version] = "1.0-beta7"

projects[metatag][version] = "1.14"

projects[mimemail][version] = "1.0-beta4"

projects[modal_forms][version] = "1.2"

projects[module_filter][version] = "2.0"

projects[mollom][version] = "2.15"

projects[morecomments][version] = "1.0-beta3"

projects[node_convert][version] = "1.2"

projects[nodequeue][version] = "2.0"

projects[oauthconnector][version] = "1.0-beta2"

projects[oauth][version] = "3.2"

projects[og][version] = "2.9"

projects[og_invite_people][version] = "1.0-beta2"

projects[override_node_options][version] = "1.13"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "2.12"

projects[phone][version] = "1.0-beta1"

projects[profile2][version] = "1.3"

projects[quicktabs][version] = "3.6"

projects[realname][version] = "1.2"

projects[recaptcha][version] = "1.13"

projects[reg_with_pic][version] = "1.0"

projects[rules][version] = "2.9"

projects[search_config][version] = "1.1"

projects[searchindex_wipe][version] = "1.1"

projects[security_review][version] = "1.2"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.6"

projects[track_field_changes][version] = "1.5"

projects[user_restrictions][version] = "1.0"

projects[user_stats][version] = "1.x-dev"

projects[usersearchtoadmin][version] = "1.1"

projects[uuid][version] = "1.0-beta1"

projects[uuid_features][version] = "1.0-alpha4"

projects[views][version] = "3.13"

projects[views_autocomplete_filters][version] = "1.2"

projects[views_data_export][version] = "3.0-beta9"

projects[views_field_view][version] = "1.2"

projects[views_php][version] = "1.0-alpha3"

projects[views_responsive_grid][version] = "1.3"

projects[views_send][version] = "1.2"

projects[views_slideshow][version] = "3.1"

projects[vscc][version] = "1.1"

projects[jcarousel][version] = "2.7"





; Themes

;projects[bootstrap][type] = theme
;projects[bootstrap][version] = 3.1-beta2



; Libraries

;libraries[backbone][download][type] = get
;libraries[backbone][download][url] = https://github.com/jashkenas/backbone/archive/1.1.2.zip

;libraries[bootstrap][download][type] = get
;libraries[bootstrap][download][url] = https://github.com/twbs/bootstrap/archive/v3.2.0.zip
;libraries[bootstrap][directory_name] = bootstrap
;libraries[bootstrap][destination] = themes/contrib/bootstrap
;libraries[bootstrap][overwrite] = TRUE

;libraries[dindent][download][type] = get
;libraries[dindent][download][url] = https://raw.githubusercontent.com/Decipher/dindent/master/src/Parser.php

;libraries[mailchimp][download][type] = get
;libraries[mailchimp][download][url] = https://bitbucket.org/mailchimp/mailchimp-api-php/get/2.0.5.zip

;libraries[modernizr][download][type] = get
;libraries[modernizr][download][url] = https://github.com/Modernizr/Modernizr/archive/v2.7.1.zip

;libraries[phpsass][download][type] = git
;libraries[phpsass][download][url] = https://github.com/Decipher/phpsass.git
;libraries[phpsass][download][revision] = eee7cdb

libraries[profiler][download][type] = get
libraries[profiler][download][url] = http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta2.zip
;libraries[profiler][download][revision] = 6655a1b
; Added support for Devel generate - https://drupal.org/node/1420344#comment-5890366
;libraries[profiler][patch][] = https://drupal.org/files/devel_generate-1420344-8.patch

;libraries[underscore][download][type] = get
;libraries[underscore][download][url] = https://github.com/jashkenas/underscore/archive/1.6.0.zip