; This file was auto-generated by drush make
core = 7.43

api = 2

; Modules
projects[views_bulk_operations][version] = "3.3"

projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][version] = "1.5"

projects[backup_migrate][version] = "3.1"

projects[better_exposed_filters][version] = "3.2"

projects[better_formats][version] = "1.0-beta1"

projects[block_class][version] = "2.1"

projects[ctools][version] = "1.7"

projects[cck][version] = "3.0-alpha3"

projects[ckeditor][version] = "1.16"

projects[colorbox][version] = "2.9"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[devel_form_debug][version] = "1.0"

projects[diff][version] = "3.2"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[entityreference_filter][version] = "1.5"

projects[entityreference_view_widget][version] = "2.0-rc6"

projects[features][version] = "2.6"

projects[media][version] = "1.5"

projects[flag][version] = "3.6"

projects[google_analytics][version] = "2.1"

projects[libraries][version] = "2.2"

projects[masquerade][version] = "1.0-rc7"

projects[module_filter][version] = "2.0"

projects[options_element][version] = "1.12"

projects[pathauto][version] = "1.2"

projects[pathologic][version] = "2.12"

projects[quicktabs][version] = "3.6"

projects[services][version] = "3.12"

projects[rules][version] = "2.9"

projects[search_krumo][version] = "1.6"

projects[token][version] = "1.6"

projects[ux_elements][version] = "1.0-beta1"

projects[variable][version] = "2.5"

projects[views][version] = "3.11"

projects[webform][version] = "4.10"


; Themes

;projects[bootstrap][type] = theme
;projects[bootstrap][version] = 3.1-beta2



; Libraries

;libraries[backbone][download][type] = get
;libraries[backbone][download][url] = https://github.com/jashkenas/backbone/archive/1.1.2.zip

;libraries[bootstrap][download][type] = get
;libraries[bootstrap][download][url] = https://github.com/twbs/bootstrap/archive/v3.2.0.zip
;libraries[bootstrap][directory_name] = bootstrap
;libraries[bootstrap][destination] = themes/contrib/bootstrap
;libraries[bootstrap][overwrite] = TRUE

;libraries[dindent][download][type] = get
;libraries[dindent][download][url] = https://raw.githubusercontent.com/Decipher/dindent/master/src/Parser.php

;libraries[mailchimp][download][type] = get
;libraries[mailchimp][download][url] = https://bitbucket.org/mailchimp/mailchimp-api-php/get/2.0.5.zip

;libraries[modernizr][download][type] = get
;libraries[modernizr][download][url] = https://github.com/Modernizr/Modernizr/archive/v2.7.1.zip

;libraries[phpsass][download][type] = git
;libraries[phpsass][download][url] = https://github.com/Decipher/phpsass.git
;libraries[phpsass][download][revision] = eee7cdb

libraries[profiler][download][type] = get
libraries[profiler][download][url] = http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta2.zip
;libraries[profiler][download][revision] = 6655a1b
; Added support for Devel generate - https://drupal.org/node/1420344#comment-5890366
;libraries[profiler][patch][] = https://drupal.org/files/devel_generate-1420344-8.patch

;libraries[underscore][download][type] = get
;libraries[underscore][download][url] = https://github.com/jashkenas/underscore/archive/1.6.0.zip