<?php
/**
 * @file
 * Collabco stock loader module.
 */

/**
 * Implements hook_form_alter().
 */
function collabco_stock_loader_form_alter(&$form, &$form_state, $form_id) {
  if ((arg(0) == "node") && (arg(1) == "add")) {
    if(isset($form['field_featured_picture'])) {
      $form['field_featured_picture']['und'][0]['#title'] = "Featured Image";
      //$form['field_featured_picture']['und'][0]['#description'] = include('search.html');
      $form['field_featured_picture']['#attached']['js'] = array(drupal_get_path('module', 'collabco_stock_loader') . '/inc/ajax.js',);
      $form['field_featured_picture']['#suffix'] = '
      <input type="text" name="input_val" id="input_val" >

      <br>
      <div id="created"><b>Stock images will be loaded here...</b></div>
      <br><br>
      ';
      // print "<pre>";
      // print_r($form);
      // print_r($form['field_featured_picture']);
      //die();
    }
    if(isset($form['field_featured_hub_image'])) {
            $form['field_featured_hub_image']['und'][0]['#title'] = "Featured Image";
      //$form['field_featured_picture']['und'][0]['#description'] = include('search.html');
      $form['field_featured_hub_image']['#attached']['js'] = array(drupal_get_path('module', 'collabco_stock_loader') . '/inc/ajax.js',);
      $form['field_featured_hub_image']['#suffix'] = '
      <input type="text" name="input_val" id="input_val" placeholder="Start typing a keyword..." >

      <br>
      <div id="created"><b>Stock images will be loaded here...</b></div>
      <br><br>
      ';
      // print "<pre>";
      // // print_r($form);
      // print_r($form['field_featured_hub_image']);
      // die();
    }
  }
}
