<?php

/**
 * @file collabco_login.module
 *
 * Enforce that the username field is used for the email address and the email
 * address field suppressed (but still stored on the db), on these pages:
 * o registration form
 * o login form (/user page and login block)
 * o account edit form
 *
 * Override user_theme() to display the user's Full Name account field.
 */

/**
 * Implements hook_form_FORMID_alter().
 *
 * For user_register form
 */
function collabco_login_form_user_register_form_alter(&$form, &$form_state) {
  _collabco_login_form_alterations($form, $form_state);
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * For user_login form
 */
function collabco_login_form_user_login_alter(&$form, &$form_state) {
  _collabco_login_form_alterations($form, $form_state);
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * For user_login_block
 */
function collabco_login_form_user_login_block_alter(&$form, &$form_state) {
  _collabco_login_form_alterations($form, $form_state);
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * For user_profile_form
 */
function collabco_login_form_user_profile_form_alter(&$form, &$form_state) {
  _collabco_login_form_alterations($form, $form_state);
}

/*
 * Upon login and on user profile edits, user should be redirected to homepage.
 *
 * Exception: first-time login or password reset links are not affected, e.g.
 *  "user/reset/15/1467161593/JyRtjZ6gsEukoQ7EWA0_BSFu5Dfonyk64xuoeuLrqjQ/login"
 */
function collabco_login_form_user_profile_form_submit(&$form, &$form_state) {
  $form_state['redirect'] = '';
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Replace username theme by our version, which displays the full_name field
 * instead. See function collabco_login_username().
 */
function collabco_login_theme_registry_alter(&$theme_registry) {
  $theme_registry['username']['function'] = 'collabco_login_username';
}

/*
 * Overrides theme_username() to display user's Full Name, instead of username.
 *
 * @param array $variables
 */
function collabco_login_username($variables) {
  if (!empty($variables['uid'])) {
    // Load the full account object to access the Full Name field.
    $user = user_load($variables['uid']);
    if ($user && !empty($user->field_full_name[LANGUAGE_NONE][0])) {
      $variables['name'] = $user->field_full_name[LANGUAGE_NONE][0]['value'];
    }
  }
  return theme_username($variables);
}

function collabco_login_mail_validate(&$form, &$form_state) {
  if ($error = user_validate_mail($form_state['values']['name'])) {
    //drupal_set_message(t('Please use valid email address as your username.'), 'warning');
    form_set_error('name', $error);
  }
  else {
    $form_state['values']['mail'] = $form_state['values']['name'];
  }
}

function _collabco_login_form_alterations(&$form, &$form_state) {
  if (empty($form['account'])) {
    $section = &$form;
  }
  else {
    $section = &$form['account'];
  }
  $section['name']['#title'] = t('E-mail address');
  $section['name']['#description'] = t('Make sure to enter a valid email address, as it will be used for system notifications, like password reset instructions.');
  $section['name']['#element_validate'][] = 'collabco_login_mail_validate';

  $section['pass']['#description'] = t('Enter the password that accompanies your email.');

  // Suppress Mail field
  $section['mail']['#required'] = FALSE;
  $section['mail']['#access'] = FALSE;

  $form['#submit'][] = 'collabco_login_form_user_profile_form_submit';
}

/**
 * Implements hook_token_info_alter().
 */
function collabco_login_token_info() {

  $info['tokens']['user']['first-name'] = array(
    'name' => t('First name'),
    'description' => t("User's full name up to the first space"),
  );
  $info['tokens']['user']['last-name'] = array(
    'name' => t('Last name'),
    'description' => t("User's full name from the first space, blank if there's no space."),
  );
  return $info;
}


/**
 * Implements hook_tokens().
 *
 * Adds two user tokens: user:first-name and user:last-name.
 */
function collabco_login_tokens($type, $tokens, array $data = array(), array $options = array()) {

  $replacements = array();

  if ($type == 'user' && !empty($data['user'])) {

    list($first_name, $last_name) = collabco_login_user_names($data['user']);

    foreach ($tokens as $name => $original) {

      switch ($name) {
        case 'first-name':
          $replacements[$original] = $first_name;
          break;

        case 'last-name':
          $replacements[$original] = $last_name;
          break;
      }
    }
  }
  return $replacements;
}

function collabco_login_user_names($user) {
  if (empty($user->field_full_name[LANGUAGE_NONE])) {
    $full_name = trim($user->name);
  }
  else {
    $full_name = trim($user->field_full_name[LANGUAGE_NONE][0]['value']);
  }
  $first_space = strpos($full_name, ' ');
  $first_name = $first_space ? substr($full_name, 0, $first_space) : $full_name;
  $last_name  = $first_space ? substr($full_name, $first_space + 1) : '';

  return array($first_name, ucwords($last_name));
}