<?php
/**
 * @file
 * Demo to use any (custom) theme setting or Drupal variable in any of your
 * theme or module style sheets (see https://drupal.org/project/style_settings).
 */

/**
 * Implements hook_page_build().
 */
function collabco_color_page_build(&$page) {
 
  drupal_add_css(drupal_get_path('module', 'collabco_color') . '/css/jquery.gradientPicker.css', array(
    'group' => CSS_DEFAULT,
    'every_page' => TRUE,
  ));
}



/**
 * Implements hook_page_build().
 */
// function style_settings_page_build(&$page) {
  // drupal_add_css(drupal_get_path('module', 'style_settings') . '/css/style_settings.css', array(
  //   'group' => CSS_DEFAULT,
  //   'every_page' => TRUE,
  // ));
  // // Make sure the site's custom CSS is processed last.
  // if (file_exists(drupal_get_path('module', 'style_settings') . '/css/custom.css')) {
  //   drupal_add_css(drupal_get_path('module', 'style_settings') . '/css/custom.css', array(
  //     'group' => CSS_THEME,
  //     'every_page' => TRUE,
  //     'weight' => 99,
  //   ));
  // }
// }


/**
 * Implements hook_menu().
 */
function collabco_color_menu() {
  // Here placed in the 'config/SYSTEM' section. Put it in the appropriate
  // section.
  $items['admin/config/system/collabco_color'] = array(
    'title' => 'Collabco Color',
    'description' => 'Collabco Color Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('collabco_color_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'collabco_color.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_element_info().
 */
function collabco_color_element_info() {
  $colornames = l(t('valid color names'), 'https://en.wikipedia.org/wiki/Web_colors#X11_color_names', array(
    'attributes' => array(
      'title' => t('Web colors - Wikipedia, the free encyclopedia'),
      'target' => '_blank',
    ),
  ));


  $types['collabco_color_gradientpicker'] = array(
    '#input' => TRUE,
    '#type' => 'textfield',
    '#theme' => array('textfield'),
    '#theme_wrappers' => array('form_element'),
    '#autocomplete_path' => FALSE,
    '#element_validate' => array('collabco_color_gradient_validate'),
    '#size' => 500,
    '#maxlength' => 500,
    '#description' => t('Also shorthand (like #fff) and !colornames are accepted.', array('!colornames' => $colornames)),
    '#prefix' => '<div class="form-item form-type-collabco-color-gradient-picker">',
    '#suffix' => '<div class="grad_ex"></div></div>',
    '#default_value' => '',
    '#attributes' => array('class' => array('collabco-gradient-picker-input')),
    '#attached' => array(
      'library' => array(array('system', 'jquery')),
      'js' => array(drupal_get_path('module', 'collabco_color') . '/js/collabco-color-gradientpicker.js',
                    drupal_get_path('module', 'collabco_color') . '/js/jquery-gradient/plugin/jquery.gradientParser.js',
                    drupal_get_path('module', 'collabco_color') . '/js/jquery-gradient/vendor/jqueryUI-custom.js',
                    drupal_get_path('module', 'collabco_color') . '/js/jquery-gradient/vendor/jqPlugins/colorpicker/js/colorpicker.js',
                    drupal_get_path('module', 'collabco_color') . '/js/jquery-gradient/plugin/jquery.gradientPicker.js')
    ),
  );


  return $types;
}

 /* Validates that the input value matches a Gradient color.
 */
function collabco_color_gradient_validate($element, &$form_state) {

}
