<?php
/**
 * @file
 * Collabco Settings module
 */

/**
 * Implements hook_variable_info().
 */
function collabco_settings_variable_info($options) {
  $variable['collabco_inactivity_period_collab'] = array(
    'title' => t('Select the period'),
    'description' => t('Select the period to check for inactivity within Collaboartion for notifying community moderators'),
    'type' => 'select_number',
    'default' => 30,
    'options' => array(1, 5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 80, 90, 100, 150, 200, 250, 300, 350, 400, 500),
  );
  $variable['collabco_inactivity_archived_period_collab'] = array(
    'title' => t('Select the period'),
    'description' => t('Select the period to check for inactivity within Collaboration for archiving &  notification'),
    'type' => 'select_number',
    'default' => 90,
    'options' => array(1, 5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 80, 90, 100, 150, 200, 250, 300, 350, 400, 500),
  );
  return $variable;
}

/**
 * Implements hook_menu().
 */
function collabco_settings_menu() {
  return array(
    'admin/config/collabco-settings' => array(
      'page callback' => 'collabco_settings_admin_settings',
      'access arguments' => array(TRUE),
      'type' => MENU_NORMAL_ITEM,
      'title' => 'Collabco Settings for Collaboration',
    ),
  );
}

/**
 * Implements hook_admin_settings().
 */
function collabco_settings_admin_settings() {
  $form = drupal_get_form('variable_module_form', 'collabco_settings');
  return $form;
}

/**
 * Implements hook_help().
 */
function collabco_settings_help($path, $arg) {
  switch ($path) {
    case "admin/help#collabco_settings":
      return '<p>' . t("Collabco Setting") . '</p>';
  }
}


/********CKEditor plugins********/
function collabco_settings_ckeditor_plugin()
{
    $module_path = drupal_get_path('module', 'collabco_settings');
    $plugins     = array();
   
    $plugins['confighelper'] = array(
        'name'    => 'confighelper',
        'desc'    => t(' CKEditor: Configuration helper plugin'),
        'path'    => $module_path . '/ckeditor-plugins/confighelper/',
        'default' => 't'
    );
    return $plugins;
}